version: "3.9"

services:
  aspnetcore-service:
    build:
      context: .
      dockerfile: ./Sidecard/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SIDECAR_ADDRESS=http://localhost:8080/
    depends_on:
      - nats
    networks:
      - internal
      - external
    restart: always

  nats:
    image: nats:latest
    ports:
      - "4222:4222"
    environment:
      - NATS_JETSTREAM=true

networks:
  internal: {}
  external: {}
