FROM alpine

WORKDIR /Sidecard

ENV NODE_ENV=production

COPY ./moleculer-sidecar-alpine ./moleculer-sidecar

RUN apk add --no-cache libstdc++

EXPOSE 5103

ENTRYPOINT ["/Sidecard/moleculer-sidecar"]
