version: "3.9"

services:
  sidecar:
    image: sidecar-demo-main
    build:
      context: ./
      dockerfile: Dockerfile-alpine
    environment:
      SIDECAR_PORT: 5103
      TRANSPORTER: nats://nats:4222
    depends_on:
      - nats
    networks:
      - internal
      - external
    restart: always
    
  aspnetcore-service:
    build:
      context: .
      dockerfile: ./Sidecard/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SIDECAR_ADDRESS=http://sidecar:5103
    depends_on:
    networks:
      - internal
    restart: always

  nats:
    image: nats:latest
    ports:
      - "4222:4222"
    networks:
      - external
    restart: always

networks:
  internal: {}
  external: {}
